### PR TITLE
FEA-2048: Ignore nested subpackages

### LINKED ISSUE #59: Running on nested package throws exception
Given the following common project structure

```
./packageA
  pubspec.yaml
  app
    pubspec.yaml
```

If scip-dart is run at the root directory, the following error is thrown:

```
ERROR: Unable to locate packageConfig
```

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
# [FEA-2048](https://jira.atl.workiva.net/browse/FEA-2048)
Issue Status

Closes #59 

Running `scip-dart` on a dart package with a nested pubspec.yaml file would result in an error (see #59), this pr ignores any subdirectories that declare their own pubspec.yaml file

If nested directories want to be indexed as well, scip-dart can just be re-run on that path

Also, as a QoL update, if the root path provided to `scip_dart ./path` did not contain a pubspec.yaml file, the cli logs an error and fails with a non-zero exit code.

some CI changes are in this pr as well:
- fixed a bug where formatting was not failing when it detected changes
- added an analysis step to ensure analysis passes, implemented default analysis rules, and disabled implicit casts

### CODE REVIEW

File: lib/src/utils.dart [hunk 1]
```diff
@@ -1,8 +1,20 @@
...
 import 'package:scip_dart/src/flags.dart';
 
+/// Returns a list of all the pubspec.yaml paths under a directory.
+/// Will recurse into child folders, will not follow links.
+Future<List<String>> pubspecPathsFor(String rootDirectory) async {
+  return Directory(rootDirectory)
+    .list(recursive: true, followLinks: false)
+    .where((file) => p.basename(file.path) == 'pubspec.yaml')
+    .map((file) => file.path)
+    .toList();
```
Comment (matthewnitschke-wk) [inline lib/src/utils.dart:15]: I tested the performance of this on a few different large dart packages

For a package that had 65,000 files, this took 300ms. An acceptable performance hit for a repo of that size

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

File: .github/workflows/tests.yaml [hunk 2]
```diff
@@ -49,7 +49,12 @@ jobs:
 
     strategy:
       matrix:
-        repo: ["Workiva/over_react", "rrousselGit/provider", "dart-lang/args"]
+        repo: [
+          "Workiva/over_react",
+          "Workiva/w_module",
```
Comment (matthewnitschke-wk) [inline .github/workflows/tests.yaml:54]: w_module has a nested `pubspec.yaml` file in [example](https://github.com/Workiva/w_module/blob/master/example/pubspec.yaml)

Add it as a consumer to verify this new functionality of not breaking on nested packages

File: lib/src/indexer.dart [hunk 3]
```diff
@@ -15,35 +18,55 @@ Future<Index> indexPackage(
...
-      toolInfo: ToolInfo(
-        name: 'scip-dart',
-        version: '0.0.1',
-        arguments: [],
-      ));
+    projectRoot: 'file:/' + dirPath,
+    textDocumentEncoding: TextEncoding.UTF8,
+    toolInfo: ToolInfo(
+      name: 'scip-dart',
+      version: '0.0.1',
```
Comment (evanweible-wf) [inline lib/src/indexer.dart:37]: Unrelated but should this match the version of this library? Do we need to move this to a constant somewhere and configure the release event to bump it as well?

**Review by evanweible-wf — APPROVED** [review]

File: lib/src/indexer.dart (hunk 3 above)
Comment (matthewnitschke-wk) [reply lib/src/indexer.dart:37]: Yea, ideally we do

I didn't love the idea of relying on a release event (if for whatever reason scip-dart changed owners outside of workiva one day) and wanted the solution to be baked into the project

I have an issue tracking this [here](https://github.com/Workiva/scip-dart/issues/43) and a spike pr for one of the solutions here: https://github.com/Workiva/scip-dart/pull/45. Just haven't pushed on wrapping that up yet

**Comment by matthewnitschke-wk** [comment]
QA +1

CI passes and verified that indexing works on some packages locally

**Comment by matthewnitschke-wk** [comment]
🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM
