### PR TITLE
FEDX-2227: Fixed logic for constructor references

### LINKED ISSUE #163: Constructor references point to class definitions
Given the following:

```dart
class Foo {
  factory Foo()
//        ^^^ Foo#`<constructor>`().
}

void main() {
  final a = Foo();
//          ^^^ Foo#
}
```

References to the constructor incorrectly reference the class symbol, not the constructor

### LINKED ISSUE #164: Constructors are incorrectly references to the class
```dart
class Foo {
  Foo()
//^^^ definition /Foo#`<constructor>`().
//^^^ reference /Foo#
}
```

The constructor isn't a reference to the class, this should be removed

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
# [FEDX-2227](https://jira.atl.workiva.net/browse/FEDX-2227)
Issue Status

Closes #164 
Closes #163

### CODE REVIEW

File: snapshots/output/basic-project/lib/main.dart [hunk 1]
```diff
@@ -95,7 +95,7 @@
 //                  ^^^ reference scip-dart pub dart:core 2.19.0 dart:core/`int.dart`/int#
 //                      ^^^^^ definition local 5
     Foo(1, value: true, value2: '');
-//  ^^^ reference scip-dart pub dart_test 1.0.0 lib/`other.dart`/Foo#
+//  ^^^ reference scip-dart pub dart_test 1.0.0 lib/`other.dart`/Foo#`<constructor>`().
```
Comment (matthewnitschke-wk) [inline snapshots/output/basic-project/lib/main.dart:98]: Now we're correctly referencing `<constructor>`, fixed by: https://github.com/Workiva/scip-dart/pull/165/files#diff-0ab533d80a9e11da530798d9b92364a97087c4754ab8251de00d85b635c6a4e4R76

File: snapshots/output/basic-project/lib/more.dart [hunk 2]
```diff
@@ -77,6 +76,13 @@
       }
     }
   
+    factory Animal.cat() => Animal('Timmy', type: AnimalType.cat);
```
Comment (matthewnitschke-wk) [inline snapshots/output/basic-project/lib/more.dart:79]: Very frustratingly, in named constructors, `Animal.cat()` there is only a single identifier

Screenshot 2024-12-19 at 10 57 04 AM

This isn't the case for SimpleIdentifiers for the call sight, but only the constructor declarations

The result of this, is we can only index a single element here, and I've decided to index, the arguably more important, definition for `cat()`

```dart
factory Animal.cat() => ...
//      ^^^^^^ NOT INDEXED
//             ^^^ definition ... Animal#cat().
```

Solving this is a problem for another day...

Comment (matthewnitschke-wk) [reply snapshots/output/basic-project/lib/more.dart:79]: I created a ticket to track this here: https://github.com/Workiva/scip-dart/issues/166

File: lib/src/symbol_generator.dart [hunk 3]
```diff
@@ -44,6 +44,38 @@ class SymbolGenerator {
     } else if (node is SimpleIdentifier) {
       var element = node.staticElement;
 
+      // A SimpleIdentifier with a direct parent of a ConstructorDeclaration
+      // is the reference to the class itself. In scip, we want to ignore
+      // this as the constructor has its own definition, and only that
```
Comment (alanknight-wk) [inline lib/src/symbol_generator.dart:49]: Is there a missing end of sentence here?

File: lib/src/symbol_generator.dart [hunk 4]
```diff
@@ -44,6 +44,38 @@ class SymbolGenerator {
...
+        return null;
+      }
+
+      // if we're nested under a ConstructorName identifier, use the constructor
+      // as the element to annotate instead of the reference to the Class
+      final parentConstructor = node.thisOrAncestorOfType<ConstructorName>();
+      if (parentConstructor != null) {
+        // ConstructorNames can also include an import PrefixIdentifier: `math.Rectangle()`
+        // both 'math' and 'Rectangle' are SimpleIdentifiers. We only want the constructor
+        // element fo 'Rectangle' in this case
```
Comment (alanknight-wk) [inline lib/src/symbol_generator.dart:60]: spelling nit: 'fo'

**Review by alanknight-wk — DISMISSED** [review]
Two comment nits, otherwise LGTM

**Comment by matthewbelisle-wf** [comment]
Going to close and re-open this, trying to fix one of the CI errors.

**Review by alanknight-wk — APPROVED** [review]

**Comment by matthewnitschke-wk** [comment]
QA +1

- [x]  CI does indeed pass, snapshots look good!

🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM
